= MidPilot Validator service REST API

Spring Boot REST API that provides validation and conversion capabilities for midpoint code and data.
The service exposes two endpoints:

== Build and Run

Using Maven:

[source,bash]
----
mvn clean spring-boot:run
----

The service will start on:

----
http://localhost:8080
----

== Endpoints

=== Validate

Validates the provided input and returns validation results.

*Method:* `POST` +
*Path:* `/validate` +
*Consumes:* `application/json`, `application/xml`, `application/yaml` +
*Produces:* `application/json` +

==== Query Parameters

[cols="1,1,1,2",options="header"]
|===
| Name | Type | Required | Description

| objectType
| string
| No
| Object type or Complex type definition against which the content body should be validated

| itemPath
| string
| No
| Path of the item to definition against which the content body should be validated
|===

==== Request Example (Invalid)

[source,bash]
----
curl --location 'http://localhost:8080/validate' \
--header 'Content-Type: application/json' \
--data '{
 "mapping": {
    "name": "givenName-familyName-to-cn",
    "source": [
      { "path": "$focus/givenName" },
      { "path": "$focus/familyName" }
    ],
    "expression": {
      "script": {
        "code": "givenName + ' ' + familyName"
      }
    },
    "condition": {
      "script": {
        "code": "givenName != null && familyName != null"
      }
    },
    "target": {
      "path": "$projection/attributes/cn"
    }
  }
}'
----

==== Response Example (Invalid)

[source,json]
----
{
    "logs": [
        {
            "type": "ERROR",
            "specification": "MISSING_DEFINITION",
            "location": {
                "line": 2,
                "char": 14,
                "source": "unknown"
            },
            "message": "Cannot parse object from element 'mapping', there is no definition for that element",
            "technicalMessage": {
                "message": "Cannot parse object from element '%s', there is no definition for that element can you clarify the definition based on the expected definitions from list: '%s'",
                "arguments": [
                    {
                        "value": "com.evolveum.midpoint.prism.path.ItemName$WithoutPrefix",
                        "type": "QNAME"
                    },
                    {
                        "definitions": [
                            "PCD:{http://midpoint.evolveum.com/xml/ns/public/common/common-3}mapping {http://midpoint.evolveum.com/xml/ns/public/common/common-3}AbstractMappingType[0,1],RAM",
                            "PCD:{http://midpoint.evolveum.com/xml/ns/public/common/common-3}mapping {http://midpoint.evolveum.com/xml/ns/public/common/common-3}ObjectTemplateMappingType[0,-1],RAM",
                            "PCD:{http://midpoint.evolveum.com/xml/ns/public/common/common-3}mapping {http://midpoint.evolveum.com/xml/ns/public/common/common-3}MappingType[0,-1],RAM",
                            "PCD:{http://midpoint.evolveum.com/xml/ns/public/common/common-3}mapping {http://midpoint.evolveum.com/xml/ns/public/common/common-3}ObjectTemplateMappingType[0,-1],RAM",
                            "PCD:{http://midpoint.evolveum.com/xml/ns/public/common/common-3}mapping {http://midpoint.evolveum.com/xml/ns/public/common/common-3}MetadataMappingType[0,-1],RAM",
                            "PCD:{http://midpoint.evolveum.com/xml/ns/public/common/common-3}mapping {http://midpoint.evolveum.com/xml/ns/public/common/common-3}MetadataMappingType[0,-1],RAM",
                            "PCD:{http://midpoint.evolveum.com/xml/ns/public/common/common-3}mapping {http://midpoint.evolveum.com/xml/ns/public/common/common-3}AutoassignMappingType[0,-1],RAM",
                            "PCD:{http://midpoint.evolveum.com/xml/ns/public/common/common-3}mapping {http://midpoint.evolveum.com/xml/ns/public/common/common-3}InboundMappingType[0,-1],RAM",
                            "PCD:{http://midpoint.evolveum.com/xml/ns/public/common/common-3}mapping {http://midpoint.evolveum.com/xml/ns/public/common/common-3}MappingType[0,-1],RAM",
                            "PCD:{http://midpoint.evolveum.com/xml/ns/public/common/common-3}mapping {http://midpoint.evolveum.com/xml/ns/public/common/common-3}MappingType[1,1],RAM"
                        ],
                        "type": "DEFINITION_LIST"
                    }
                ]
            }
        }
    ]
}
----


==== Request Example (Valid)

[source,bash]
----
curl --location 'http://localhost:8080/validate' \
--header 'Content-Type: application/json' \
--data '{
    "schemaHandling": {
        "objectType": {
            "kind": "account",
            "intent": "default",
            "default": "true",
            "delineation": {
                "objectClass": "user"
            },
            "focus": {
                "type": "UserType"
            },
            "attribute": {
                "ref": "name",
                "correlator": "",
                "inbound": {
                    "strength": "strong",
                    "target": {
                        "path": "name"
                    }
                },
                "outbound": {
                    "strength": "strong",
                    "source": {
                        "path": "name"
                    }
                }
            }
        }
    }
}'
----

==== Response Example (Valid)

[source,json]
----
{
    "logs": []
}
----

=== Convert

Convert the provided Midpoint object and returns converted to target language.

==== Query Parameters

*Method:* `POST` +
*Path:* `/convert` +
*Consumes:* `application/json`, `application/xml`, `application/yaml` +
*Produces:* `application/json`, `application/xml`, `application/yaml` +

[cols="1,1,1,2",options="header"]
|===
| Name | Type | Required | Description

| targetLanguage
| string
| Yes
| The language you want to convert.
|===


==== Request Example

[source,bash]
----
curl --location 'http://localhost:8080/convert?targetLanguage=json' \
--header 'Content-Type: application/xml' \
--data '<attribute>
          <ref>ri:fullname</ref>
          <inbound>
              <strength>strong</strength>
              <target>
                <path>fullName</path>
              </target>
          </inbound>
          <outbound>
              <strength>strong</strength>
              <source>
                <path>fullName</path>
              </source>
          </outbound>
        </attribute>'
----

==== Response Example

[source,json]
----
{
    "#attribute": {
        "#ref": "ri:fullname",
        "#inbound": {
            "#strength": "strong",
            "#target": {
                "#path": "fullName"
            }
        },
        "#outbound": {
            "#strength": "strong",
            "#source": {
                "#path": "fullName"
            }
        }
    }
}
----


== Commands

Validate object (full or snippet) input as string.

[source,bash]
----
java -jar validation-services.jar validate <code>
----

Validate object (all or snippet) input as path of file.
Required flag -f.

[source,bash]
----
java -jar validation-services.jar validate <path-of-file> -f
----

Validate all objects (xml, json, yaml) from midpoint-samples maven repository.

[source,bash]
----
java -jar validation-services.jar validate -midpoint-samples
----

NOTE: or shortcut of -midpoint-samples

[source,bash]
----
java -jar validation-services.jar validate -ms
----

Convert object (full or snippet) input as string.
[source,bash]
----
java -jar validation-services.jar convert <code>
----
