= MidPilot Validator service REST API

Spring Boot REST API that provides validation and conversion capabilities for midpoint code and data.

For more information with examples, see the https://docs.evolveum.com/midpoint/projects/midPilot/midpilot-validator/[documentation MidPilot Validator service].


== Build and Run

Using Maven:

[source,bash]
----
mvn clean spring-boot:run
----

The service will start on:

----
http://localhost:8080
----

== Endpoints
The service exposes two endpoints:

=== Validate

Validates the provided input and returns validation results.

*Method:* `POST` +
*Path:* `/validate` +
*Consumes:* `application/json`, `application/xml`, `application/yaml` +
*Produces:* `application/json` +

==== Query Parameters

[cols="1,1,1,2",options="header"]
|===
| Name | Type | Required | Description

| objectType
| string
| No
| Object type or Complex type definition against which the content body should be validated

| itemPath
| string
| No
| Path of the item to definition against which the content body should be validated
|===


=== Convert

Convert the provided Midpoint object and returns converted to target language.

==== Query Parameters

*Method:* `POST` +
*Path:* `/convert` +
*Consumes:* `application/json`, `application/xml`, `application/yaml` +
*Produces:* `application/json`, `application/xml`, `application/yaml` +

[cols="1,1,1,2",options="header"]
|===
| Name | Type | Required | Description

| targetLanguage
| string
| Yes
| The language you want to convert.
|===

== Commands

Validate object (full or snippet) input as string.

[source,bash]
----
java -jar validation-services.jar validate <code>
----

Validate object (all or snippet) input as path of file.
Required flag -f.

[source,bash]
----
java -jar validation-services.jar validate <path-of-file> -f
----

Validate all objects (xml, json, yaml) from midpoint-samples maven repository.

[source,bash]
----
java -jar validation-services.jar validate -midpoint-samples
----

NOTE: or shortcut of -midpoint-samples

[source,bash]
----
java -jar validation-services.jar validate -ms
----

Convert object (full or snippet) input as string.
[source,bash]
----
java -jar validation-services.jar convert <code>
----

